config/routes.rb
Rails.application.routes.draw do
  post 'session/login'

  get 'session/logout'
  root :to => 'matchs#index'
  get 'teams/index'
  post 'teams/index' 
  resources :users

  resources :session
 
  resources :matchs
  get 'matchs/index'
  post 'matchs/index' 
  resources :bets

  post 'bets/new1'

end

app/models/bet.rb
class Bet < ActiveRecord::Base
	belongs_to :team, :class_name => 'User'
	belongs_to :match, :class_name => 'Match'
end

app/models/match.rb
class Match < ActiveRecord::Base
	enum match_type: [ :domestic, :international ]
	belongs_to :team_1, :class_name => 'Team'
   belongs_to :team_2, :class_name => 'Team'
   belongs_to :team

	def self.all_types
		%w(Domestic International)
	end

end

app/models/team.rb
class Team < ActiveRecord::Base
	enum team_type: [ :domestic, :international ]
	has_many :matches
	
	def self.all_types
		%w(Domestic International)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
	def index
		@bets = Bet.all
		userID = session[:currUserID] || 0
		if userID != 0
			@user = User.find(userID)
			#puts 'USERID:', @user.Name
		end
	end

	def new
		#puts params.inspect
		userID = session[:currUserID] || 0
		if userID != 0
			id = params[:format]
			puts id
			@match = Match.find(id)
			@user = User.find(userID)
			@team1 = Team.find(@match.team_1_id)
			@team2 = Team.find(@match.team_2_id)
		else
			flash[:status] = "Please sign in to place a bet."
			redirect_to matchs_path
		end
	end

	def new1
		#puts params.inspect
		#b=Bet.create()
		#b.update_attributes(:matchID_id=>@match,)
		value = params[:amount]
		matchID = params[:matchID]
		team = params[:team]
		@user = User.find(session[:currUserID])
		#puts value, matchID, team
		@match = Match.find(matchID)
		if @match.blank?
			flash[:status] = "Wrong matchID entered."
			redirect_to new_bet_path(matchID)
		end
		if value.to_i > @user.Balance
			puts "Not enough balance"
			flash[:status] = "You do not have enough money."
			redirect_to new_bet_path(matchID)
		else
			b=@user.Balance
			newBalance = b-value.to_i
			@user.update_attributes(:Balance=>newBalance)
			puts newBalance
			b=Bet.create()
			id=session[:currUserID]
			b.update_attributes(:matchID_id=>matchID, :userID_id=>id, :value=>value)
			b.save
			@bets = Bet.where("name is ?", @user.Name)
			flash[:status] = "Bet was successfully placed."
			redirect_to bets_path
		end
	end
end

app/controllers/matchs_controller.rb
class MatchsController < ApplicationController
	def index
		@all_types = Match.all_types
		userID = session[:currUserID] || 0
		if userID != 0
			@user = User.find(userID)
		end
		@selected_types = params[:type] || {}
		if @selected_types != {}
			if @selected_types.size == 1
				vals = @selected_types.map { |r| if r.first == 'International'
																1
															else
																0
															end}
				query = vals.map { |r| "match_type is '#{r}'"}
				@matches = Match.where(query)
				return @matches
			end	
		end
		@matches = Match.all
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def index
		session[:currUserID] = nil
  end

  def login
    @user = User.find_by_Username_and_password params[:username_field], params[:password_field]
    if @user.nil?
      puts "yeska"
      flash[:status] = "Incorrect Password. Try again."
      redirect_to root_path
    else
      puts "noka"
      session[:currUserID] = @user.id	
		session[:currUser] = @user
      puts @user.id
      flash[:status] = "You have successfully logged in!"
      redirect_to matchs_path
    end
  end

  def logout
		@user = nil
		session[:currUserID] = nil
		redirect_to matchs_path
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

 def index
   @all_types = Team.all_types
	@selected_types = params[:types]
	if params[:types] != {}
	#	@teams = Team.find_all_by_type(@selected_types.keys)
	#	return @teams
	end
   @teams = Team.all
 end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

 def index
   @all_types = Team.all_types
	userID = session[:currUserID] || 0
	if userID != 0
		@user = User.find(userID)
	end
	@selected_types = params[:type] || {}
	if @selected_types != {}
		if @selected_types.size == 1
			vals = @selected_types.map { |r| if r.first == 'International'
															1
														else
															0
														end}
			query = vals.map { |r| "team_type is '#{r}'"}
			@teams = Team.where(query)
			return @teams
		end
	end
   @teams = Team.order(team_type: :desc)
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
	 userID = session[:currUserID] || 0
	 if userID != 0
    	@user = User.find(session[:currUserID])
    	puts 12345
	 else
		@user = nil
	 end
	
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:Name, :Username, :Balance, :DOB, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/matchs_helper.rb
module MatchsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bets/index.html.haml
%h1 All Bets

%h2 Showing all bets by #{@user.Name}

- if flash[:status]
	#notice.message= flash[:status]

= link_to 'View All Teams', teams_index_path
= link_to 'View All Matches', matchs_path

%table#bets
	%thead
		%tr
		%th User
		%th Match
		%th Value
	%tbody
	- @bets.each do |t|
		%tr
			%td= @user.Name
			%td= t.matchID_id
			%td= t.value

- if session[:currUserID]
	= link_to 'Logout', session_logout_path

app/views/bets/new.html.haml
%h1 New Bet

- if flash[:status]
	#notice.message= flash[:status]

%h3 Selected match: 

%table#Details
	%thead
		%tr
			%th Match ID
			%th Team 1
			%th Team 2
			%th Match Type
	%tbody
		%tr
			%td= @match.id
			%td= @team1.name
			%td= @team2.name
			%td= @match.match_type


= form_tag bets_new1_path, :method=>:post do
	%h3 Enter amount to bet:
	= text_field_tag(:amount)
	<br>
	%h3 Enter match ID:    
	= text_field_tag(:matchID)
	%br
	Team 1
	= radio_button_tag 'team', '1'
	Team 2
	= radio_button_tag 'team', '2'  
	<br>
	= submit_tag("Place bet")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jua 2.0</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head><h1 class='title'>Pakistan's first and premier brokerage firm</h1>
<body id="main" >


<%= yield %>

</body>
</html>

app/views/matchs/index.html.haml
%h1 All Matches

- if flash[:status]
	#notice.message= flash[:status]

- if session[:currUserID]
	Welcome, #{@user.Name}
	= link_to 'View All bets', bets_path
- else
	= link_to 'Sign In', session_index_path
	= link_to 'Sign Up', new_user_path

<br><br>

= link_to 'View All Teams', teams_index_path

<br><br>

%input{:type=>"hidden", :value=>params[:match_types], :name=>:match_types}
= form_tag matchs_index_path :method => :post do
	Filter Matches:
	- @all_types.each do |type|
		= type
		= check_box_tag "type[#{type}]",1,  @selected_types.include?(type) 
	= submit_tag 'Filter'

%input{:type=>"hidden", :value=>"null", :name=>"selected_match"}
%table#matches
	%thead
		%tr
		%th Home Team
		%th Away Team
		%th Type
		%th Bet
	%tbody
	- @matches.each do |t|
		%tr
			- if t.team_1 != nil
				%td= t.team_1.name
				%td= t.team_2.name
				%td= t.match_type
				%td= link_to 'Place Bet', new_bet_path(t.id)
				
				
				

- if session[:currUserID]
	= link_to 'Logout', session_logout_path

app/views/session/index.html.haml
- if flash[:status]
  #notice.message= flash[:status]

%p Sign in

= form_tag session_login_path do
  = text_field_tag(:username_field)
  %br
  = password_field_tag(:password_field)
  = submit_tag("Log in")

%p New here?
= link_to 'Sign up', new_user_path
%p Or
= link_to 'sign in with Facebook', new_user_path

app/views/session/login.html.erb
<h1>Session#login</h1>
<p>Find me in app/views/session/login.html.erb</p>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/session/logout.html.haml
%h1 Logged Out

= link_to 'Sign In', session_index_path
= link_to 'View All Matches', matchs_path
= link_to 'View All Teams', teams_index_path 

app/views/team/index.html.haml
%h1 All Teams

%input{:type=>"hidden", :value=>params[:types], :name=>:types}
= form_tag :method => :get do
  Include: 
  - @all_types.each do |type|
    = type
    = check_box_tag "type[#{type}]",1, true 
  = submit_tag 'Filter'

%table#teams
  %thead
    %tr
      %th Team
      %th Type
  %tbody
    - @teams.each do |t|
      %tr
        %td= t.name
        %td= t.team_type

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Username %><br>
    <%= f.text_field :Username %>
  </div>
  <div class="field">
    <%= f.label :Balance %><br>
    <%= f.number_field :Balance %>
  </div>
  <div class="field">
    <%= f.label :DOB %><br>
    <%= f.date_select :DOB %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.haml
- if flash[:status]
  #notice.message= flash[:status]

%h1 Welcome, #{@user.Name}

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.haml
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.Name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.Username %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @user.Balance %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.DOB %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>